spring.application.name=gioia
server.port=8081
spring.datasource.url= jdbc:postgresql://localhost:5432/gioia
spring.datasource.username= postgres
spring.datasource.password= ss131
spring.jpa.hibernate.ddl-auto= update
spring.jpa.properties.hibernate.use_sql_comments=true

# Log dettagliato delle query
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/gioia/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/gioia
jwt.auth.converter.resource-id=admin-cli
jwt.auth.converter.principle-attribute=preferred_username

logging.level.org.springframework.security= DEBUG




